name: opentrack
version: opentrack-2.3-rc99p14-snap1-gca299e4
summary: Head tracking software for MS Windows, Linux, and Apple OSX
description: Head tracking software for MS Windows, Linux, and Apple OSX
confinement: strict

apps:
  opentrack:
    command: opentrack-launch usr/local/bin/opentrack
    plugs:
      - unity7
      - camera
      - network-bind

parts:
  application:
    plugin: dump
    source: data
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
      # Here to make the menus work.
      # - libgtk2.0-0
    after: [qt5conf] # A wiki part
